- _target_: ironlib.torchrl.envs.ReshapeTransform
  in_keys: ["policy"]
  out_shape: [-1, 3]  # reshape to preserve geometry information

- _target_: ironlib.torchrl.envs.NDVecNorm
  in_keys: ["policy"]
  shapes: [3]
  decay: 0.99999
  eps: 1e-2

- _target_: torchrl.envs.FlattenObservation
  in_keys: ["policy"]
  first_dim: -2
  last_dim: -1

- _target_: torchrl.envs.ClipTransform
  in_keys: ["policy"]
  low: -50.0
  high: 50.0

- _target_: torchrl.envs.RewardSum

- _target_: torchrl.envs.StepCounter