# output paths for hydra logs
run:
    dir: logs/geometry_rl_iclr/${experiment_name}/${now:%Y-%m-%d_%H-%M-%S-%f}
sweep:
    dir: logs/geometry_rl_multiruns_iclr/${experiment_name}/${now:%Y-%m-%d_%H-%M-%S-%f}
    subdir: ${hydra.job.override_dirname}

job:
  # you can set here environment variables that are universal for all users
  # for system specific variables (like data paths) it's better to use .env file!
  # env_set:
  config:
    # configuration for the ${hydra.job.override_dirname} runtime variable
    override_dirname:
      kv_sep: '='
      item_sep: '/'