_target_: ironlib.modules.pyg_models.hetero_gnn.HeteroGNN
name: Hetero-GNN  # for logging purposes

latent_dim: &latent_dim 64
hidden_dim: 64
output_dim: 64

node_encoder_layers: 2
edge_encoder_layers: 2
node_decoder_layers: 2
shared_processor: False

num_messages: 2
message_passing:
  
  - processor:
      _target_: con_mgn.models.networks.ProcessorLayer
      update_edge: False
      in_channels: *latent_dim
      out_channels: *latent_dim
    code: [1, 0]
    
  - processor: 
      _target_: con_mgn.models.networks.ProcessorLayer
      update_edge: False
      in_channels: *latent_dim
      out_channels: *latent_dim
    code: [0, 1]

  - processor: 
      _target_: con_mgn.models.networks.ProcessorLayer
      update_edge: False
      in_channels: *latent_dim
      out_channels: *latent_dim
    code: [0, 1]
